# Site settings
title: Tisha News
description: "Blog revelador e irreverente da Tisha, a lagartixa jornalista. Fofocas políticas e bastidores do poder. Descubra os segredos mais bem guardados da política!"
url: "https://tishanews.u1m.com.br/"
avatar: "https://tishanews.u1m.com.br/img/tisha.jpg"
image: "https://tishanews.u1m.com.br/img/tisha.jpg"
author:
  name: "Tisha News"
  email: "tisha@tisha.news"
  url: "https://tishanews.u1m.com.br"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-feed

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
