# Site settings
title: Lagartixaria News
description: "Blog revelador e irreverente de Tisha, a lagartixa jornalista. Fofocas políticas e bastidores do poder. Descubra os segredos mais bem guardados da política!"
url: "https://tisha.geanramos.com.br"
image: "https://tisha.geanramos.com.br/img/capa.jpg"
author:
  name: "Tisha"
  email: "tisha@lagartixaria.news"
  url: "https://tisha.geanramos.com.br"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
